eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:7000/eureka/
spring:
  application:
    name: shop-Gateway
server:
  port: 9000
zuul:
  routes:
    shop-cate-api:
      path: /cate/**
    shop-goods-api:
      path: /goods/**
    shop-member-api:
      path: /member/**
    shop-cart-api:
      path: /cart/**
fh:
  shop:
    checkUrls: /api/member/findMember,/api/member/loginOut,/api/addCartItem,/api/findCart,/api/findCartCount,/apideleteCartItem,/api/batchDeleteCartItem

